environment: dev
image:
  tag: dev
secretName: evolution-api-dev-secrets
env:
  - name: SERVER_TYPE
    value: http
  - name: SERVER_PORT
    value: '8080'
  - name: DATABASE_ENABLED
    value: 'true'
  - name: DATABASE_PROVIDER
    value: mysql
  - name: DATABASE_CONNECTION_CLIENT_NAME
    value: evolution_dev
  - name: CACHE_REDIS_ENABLED
    value: 'true'
  - name: CACHE_REDIS_PREFIX_KEY
    value: 'evolution:dev'
  - name: CACHE_REDIS_SAVE_INSTANCES
    value: 'false'
  - name: CACHE_LOCAL_ENABLED
    value: 'false'
  - name: EVOLUTION_OWNERSHIP_ENABLED
    value: 'false'
  - name: TELEMETRY_ENABLED
    value: 'false'
