environment: hlg
image:
  tag: hlg
secretName: evolution-api-hlg-secrets
env:
  - name: SERVER_TYPE
    value: http
  - name: SERVER_PORT
    value: '8080'
  - name: DATABASE_ENABLED
    value: 'true'
  - name: DATABASE_PROVIDER
    value: postgresql
  - name: DATABASE_CONNECTION_CLIENT_NAME
    value: evolution_hlg
  - name: CACHE_REDIS_ENABLED
    value: 'true'
  - name: CACHE_REDIS_PREFIX_KEY
    value: 'evolution:hlg'
  - name: CACHE_REDIS_SAVE_INSTANCES
    value: 'false'
  - name: CACHE_LOCAL_ENABLED
    value: 'false'
  - name: EVOLUTION_OWNERSHIP_ENABLED
    value: 'true'
  - name: EVOLUTION_OWNERSHIP_LEASE_TTL_MS
    value: '90000'
  - name: EVOLUTION_OWNERSHIP_RENEW_INTERVAL_MS
    value: '30000'
  - name: TELEMETRY_ENABLED
    value: 'false'
